// @ts-check

import { defineConfig } from 'oxlint';

export default defineConfig({
  plugins: ['eslint', 'import', 'jsdoc', 'promise'],
  env: {
    'shared-node-browser': true,
  },

  rules: {
    // Default ESLint rules, all set to "error" since Oxlint sets them to "warn"
    // by default.
    'eslint/constructor-super': 'error',
    'eslint/for-direction': 'error',
    'eslint/no-async-promise-executor': 'error',
    'eslint/no-caller': 'error',
    'eslint/no-class-assign': 'error',
    'eslint/no-compare-neg-zero': 'error',
    'eslint/no-cond-assign': 'error',
    'eslint/no-const-assign': 'error',
    'eslint/no-constant-binary-expression': 'error',
    'eslint/no-constant-condition': 'error',
    'eslint/no-control-regex': 'error',
    'eslint/no-debugger': 'error',
    'eslint/no-delete-var': 'error',
    'eslint/no-dupe-class-members': 'error',
    'eslint/no-dupe-else-if': 'error',
    'eslint/no-dupe-keys': 'error',
    'eslint/no-duplicate-case': 'error',
    'eslint/no-empty-character-class': 'error',
    'eslint/no-empty-pattern': 'error',
    'eslint/no-empty-static-block': 'error',
    'eslint/no-eval': 'error',
    'eslint/no-ex-assign': 'error',
    'eslint/no-extra-boolean-cast': 'error',
    'eslint/no-func-assign': 'error',
    'eslint/no-global-assign': 'error',
    'eslint/no-import-assign': 'error',
    'eslint/no-invalid-regexp': 'error',
    'eslint/no-irregular-whitespace': 'error',
    'eslint/no-iterator': 'error',
    'eslint/no-loss-of-precision': 'error',
    'eslint/no-misleading-character-class': 'error',
    'eslint/no-new-native-nonconstructor': 'error',
    'eslint/no-nonoctal-decimal-escape': 'error',
    'eslint/no-obj-calls': 'error',
    'eslint/no-self-assign': 'error',
    'eslint/no-setter-return': 'error',
    'eslint/no-shadow-restricted-names': 'error',
    'eslint/no-sparse-arrays': 'error',
    'eslint/no-this-before-super': 'error',
    'eslint/no-unassigned-vars': 'error',
    'eslint/no-unsafe-finally': 'error',
    'eslint/no-unsafe-negation': 'error',
    'eslint/no-unsafe-optional-chaining': 'error',
    'eslint/no-unused-labels': 'error',
    'eslint/no-useless-backreference': 'error',
    'eslint/no-useless-catch': 'error',
    'eslint/no-useless-escape': 'error',
    'eslint/no-useless-rename': 'error',
    'eslint/no-with': 'error',
    'eslint/require-yield': 'error',
    'eslint/use-isnan': 'error',
    'eslint/valid-typeof': 'error',

    // Extra ESLint rules that are not enabled by default, but we want to
    // enable.
    'eslint/accessor-pairs': 'error',
    'eslint/array-callback-return': 'error',
    'eslint/block-scoped-var': 'error',
    'eslint/curly': ['error', 'all'],
    'eslint/default-case': 'error',
    'eslint/default-param-last': 'error',
    'eslint/eqeqeq': ['error', 'smart'],
    'eslint/grouped-accessor-pairs': 'error',
    'eslint/guard-for-in': 'error',
    'eslint/id-length': [
      'error',
      {
        min: 2,
        properties: 'never',
        exceptionPatterns: ['_', 'a', 'b', 'i', 'j', 'k'],
      },
    ],
    'eslint/new-cap': [
      'error',
      {
        newIsCap: true,
        capIsNew: false,
      },
    ],
    'eslint/no-alert': 'error',
    'eslint/no-array-constructor': 'error',
    'eslint/no-bitwise': 'error',
    'eslint/no-constructor-return': 'error',
    'eslint/no-div-regex': 'error',
    'eslint/no-else-return': 'error',
    'eslint/no-empty-function': 'error',
    'eslint/no-eq-null': 'error',
    'eslint/no-extend-native': 'error',
    'eslint/no-extra-bind': 'error',
    'eslint/no-extra-label': 'error',
    'eslint/no-implicit-coercion': 'error',
    'eslint/no-inner-declarations': ['error', 'functions'],
    'eslint/no-labels': [
      'error',
      {
        allowLoop: false,
        allowSwitch: false,
      },
    ],
    'eslint/no-lone-blocks': 'error',
    'eslint/no-lonely-if': 'error',
    'eslint/no-loop-func': 'error',
    'eslint/no-multi-assign': 'error',
    'eslint/no-multi-str': 'error',
    'eslint/no-negated-condition': 'error',
    'eslint/no-nested-ternary': 'error',
    'eslint/no-new': 'error',
    'eslint/no-new-func': 'error',
    'eslint/no-new-wrappers': 'error',
    'eslint/no-param-reassign': 'error',
    'eslint/no-plusplus': [
      'error',
      {
        allowForLoopAfterthoughts: true,
      },
    ],
    'eslint/no-proto': 'error',
    'eslint/no-return-assign': ['error', 'except-parens'],
    'eslint/no-script-url': 'error',
    'eslint/no-self-compare': 'error',
    'eslint/no-shadow': ['error', { builtinGlobals: true }],
    'eslint/no-template-curly-in-string': 'error',
    'eslint/no-throw-literal': 'error',
    'eslint/no-unmodified-loop-condition': 'error',
    'eslint/no-unneeded-ternary': [
      'error',
      {
        defaultAssignment: false,
      },
    ],
    'eslint/no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTernary: true,
      },
    ],
    'eslint/no-unused-vars': [
      'error',
      {
        vars: 'all',
        args: 'all',
        argsIgnorePattern: '[_]+',
        ignoreRestSiblings: true,
      },
    ],
    'eslint/no-use-before-define': [
      'error',
      {
        functions: false,
      },
    ],
    'eslint/no-useless-call': 'error',
    'eslint/no-useless-computed-key': 'error',
    'eslint/no-useless-concat': 'error',
    'eslint/no-useless-constructor': 'error',
    'eslint/no-useless-return': 'error',
    'eslint/no-var': 'error',
    'eslint/no-void': 'error',
    // 'eslint/object-shorthand': 'error',
    'eslint/operator-assignment': 'error',
    'eslint/prefer-const': 'error',
    'eslint/prefer-destructuring': [
      'error',
      {
        VariableDeclarator: {
          array: false,
          object: true,
        },
        AssignmentExpression: {
          array: false,
          object: false,
        },
      },
      {
        enforceForRenamedProperties: false,
      },
    ],
    'eslint/prefer-numeric-literals': 'error',
    'eslint/prefer-promise-reject-errors': 'error',
    'eslint/prefer-rest-params': 'error',
    'eslint/prefer-spread': 'error',
    'eslint/prefer-template': 'error',
    'eslint/radix': 'error',
    'eslint/symbol-description': 'error',
    'eslint/yoda': ['error', 'never'],

    // Import rules.
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        json: 'always',
      },
    ],
    'import/first': 'error',
    'import/no-absolute-path': 'error',
    'import/no-amd': 'error',
    'import/no-anonymous-default-export': 'error',
    'import/no-duplicates': 'error',
    'import/no-dynamic-require': 'error',
    'import/no-mutable-exports': 'error',
    'import/no-named-as-default': 'error',
    'import/no-named-as-default-member': 'error',
    'import/no-named-default': 'error',
    'import/no-nodejs-modules': 'error',
    'import/no-self-import': 'error',
    'import/no-unassigned-import': 'error',
    'import/no-webpack-loader-syntax': 'error',
    'import/unambiguous': 'error',

    // JSDoc rules.
    'jsdoc/check-access': 'error',
    'jsdoc/check-property-names': 'error',
    'jsdoc/check-tag-names': 'error',
    'jsdoc/empty-tags': 'error',
    'jsdoc/implements-on-classes': 'error',
    'jsdoc/no-defaults': 'error',
    'jsdoc/require-param-name': 'error',
    'jsdoc/require-param': 'error',
    'jsdoc/require-param-description': 'error',
    'jsdoc/require-param-type': 'error',
    'jsdoc/require-property': 'error',
    'jsdoc/require-property-description': 'error',
    'jsdoc/require-property-name': 'error',
    'jsdoc/require-property-type': 'error',
    'jsdoc/require-returns': 'error',
    'jsdoc/require-returns-description': 'error',
    'jsdoc/require-returns-type': 'error',
    'jsdoc/require-yields': 'error',

    // Promise rules.
    'promise/catch-or-return': [
      'error',
      {
        allowFinally: true,
      },
    ],
    'promise/no-callback-in-promise': 'error',
    'promise/no-nesting': 'error',
    'promise/no-promise-in-callback': 'error',
    'promise/no-return-in-finally': 'error',
    'promise/param-names': [
      'error',
      {
        resolvePattern: '^_?resolve',
        rejectPattern: '^_?reject',
      },
    ],
    'promise/valid-params': 'error',
  },
});

export { createConfig } from './utils.js';
